<label	for='<?php echo $this->field_id?>'
		class='concise_prompt'><?php echo $this->field_definition['question']?></label>
<?php if(isset($this->field_definition['question_long']) && !empty($this->field_definition['question_long'])):?>
<label	for='<?php echo $this->field_id;?>'
		class='expanded_prompt'><?php echo $this->field_definition['question_long']?></label>
<?php endif;?>
<textarea
		id="<?php echo $this->field_id?>" 
		rows = 5
		name="<?php echo $this->field_name?>"
		value=""
><?php echo $this->field_definition['value']?></textarea>