<th>Use in</th>
<td>
	<ul class='subsubsub'>
		<li>
			<label class='<?php echo $this->value['form']['disabled'];?>' for="include_form_<?php echo $this->value['field'];?>">Form</label> 
					<input 	type="hidden"
							<?php echo $this->value['form']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][form][include]"
							value="" />
					<input 	<?php echo $this->value['form']['include'];?>
							<?php echo $this->value['form']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][form][include]"
							id="include_form_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['closed']['disabled'];?>' for="include_closed_<?php echo $this->value['field'];?>">Closed</label> 
					<input 	type="hidden"
							<?php echo $this->value['closed']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][closed][include]"
							value="" />
					<input 	<?php echo $this->value['closed']['include'];?>
							<?php echo $this->value['closed']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][closed][include]"
							id="include_closed_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['pending']['disabled'];?>' for="include_pending_<?php echo $this->value['field'];?>">Pending</label> 
					<input 	type="hidden"
							<?php echo $this->value['pending']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][pending][include]"
							value="" />
					<input 	<?php echo $this->value['pending']['include'];?>
							<?php echo $this->value['pending']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][pending][include]"
							id="include_pending_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['private']['disabled'];?>' for="include_private_<?php echo $this->value['field'];?>">Private</label> 
					<input 	type="hidden"
							<?php echo $this->value['private']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][private][include]"
							value="" />
					<input 	<?php echo $this->value['private']['include'];?>
							<?php echo $this->value['private']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][private][include]"
							id="include_private_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['cookie']['disabled'];?>' for="include_cookie_<?php echo $this->value['field'];?>">Resubmit</label> 
					<input 	type="hidden"
							<?php echo $this->value['cookie']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][cookie][include]"
							value="" />
					<input 	<?php echo $this->value['cookie']['include'];?>
							<?php echo $this->value['cookie']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][cookie][include]"
							id="include_cookie_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['rss']['disabled'];?>' for="include_rss_<?php echo $this->value['field'];?>">RSS</label> 
					<input 	type="hidden"
							<?php echo $this->value['rss']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][rss][include]"
							value="" />
					<input 	<?php echo $this->value['rss']['include'];?>
							<?php echo $this->value['rss']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][rss][include]"
							id="include_rss_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['results']['disabled'];?>' for="include_results_<?php echo $this->value['field'];?>">Results</label> 
					<input 	type="hidden"
							<?php echo $this->value['results']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][results][include]"
							value="" />
					<input 	<?php echo $this->value['results']['include'];?>
							<?php echo $this->value['results']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][results][include]"
							id="include_results_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['email']['disabled'];?>' for="include_email_<?php echo $this->value['field'];?>">Email</label> 
					<input 	type="hidden"
							<?php echo $this->value['email']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][email][include]"
							value="" />
					<input 	<?php echo $this->value['email']['include'];?>
							<?php echo $this->value['email']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][email][include]"
							id="include_email_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li>
			<label class='<?php echo $this->value['post']['disabled'];?>' for="include_post_<?php echo $this->value['field'];?>">Post</label> 
					<input 	type="hidden"
							<?php echo $this->value['post']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][post][include]"
							value="" />
					<input 	<?php echo $this->value['post']['include'];?>
							<?php echo $this->value['post']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][post][include]"
							id="include_post_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
		<li class="include_table">
			<label class='<?php echo $this->value['table']['disabled'];?>' for="include_table_<?php echo $this->value['field'];?>">Table</label> 
					<input 	type="hidden"
							<?php echo $this->value['table']['disabled'];?>
							name="field_definitions[<?php echo $this->value['field'];?>][table][include]"
							value="" />
					<input 	<?php echo $this->value['table']['include'];?>
							<?php echo $this->value['table']['disabled'];?>
							type="checkbox"
							name="field_definitions[<?php echo $this->value['field'];?>][table][include]"
							id="include_table_<?php echo $this->value['field'];?>"
							value="checked" />
		</li>
	</ul>
</td>