<label	for='<?php echo $this->field_id;?>'
		class='concise_prompt'><?php echo $this->field_definition['question']?></label>
<?php if(isset($this->field_definition['question_long']) && !empty($this->field_definition['question_long'])):?>
<label	for='<?php echo $this->field_id;?>'
		class='expanded_prompt'><?php echo $this->field_definition['question_long']?></label>
<ul class='options'>
<?php 
	endif;
	$cnt=0; 
	foreach($this->field_definition['options'] as $option):?>
		<li>
			<input	type="checkbox"
				<?php if (isset ( $_POST [$this->field_name] ) && in_array ( $option, ( array ) $_POST [$this->field_name] )):?>
					checked = "checked"
				<?php endif; ?>
				id="<?php echo "{$this->field_id}_{$cnt}";?>" 
				name="<?php echo $this->field_name?>[]"
				value='<?php echo $option;?>' />
			<label	for='<?php echo "{$this->field_id}_{$cnt}";?>'
					class='option'><?php echo $option;?></label>
		</li>
<?php 
		$cnt++;
	endforeach;?>
</ul>